import React from 'react'
import { Link } from 'gatsby'

import Layout from '../components/layout'

const playgroundPage = () => (
  <Layout>
    <h1 className="c-page__title">Hi from the playground page</h1>
    <p>Welcome to playground</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, assumenda, natus nisi numquam quibusdam voluptatibus optio soluta enim magnam est corporis in. Eligendi vero corporis laborum itaque ratione possimus error? ipsum dolor sit amet consectetur adipisicing elit. Voluptate laudantium iste ut tenetur sequi nostrum dolorum reprehenderit provident! Eius temporibus magnam suscipit error nulla labore, pariatur dignissimos facere possimus magni?</p>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)


export default playgroundPage
